/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AFunctionCall extends PFunctionCall
{
    private PExpression _expression_;
    private final LinkedList _arglist_ = new TypedLinkedList(new Arglist_Cast());

    public AFunctionCall()
    {
    }

    public AFunctionCall(
        PExpression _expression_,
        List _arglist_)
    {
        setExpression(_expression_);

        {
            this._arglist_.clear();
            this._arglist_.addAll(_arglist_);
        }

    }
    public Object clone()
    {
        return new AFunctionCall(
            (PExpression) cloneNode(_expression_),
            cloneList(_arglist_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFunctionCall(this);
    }

    public PExpression getExpression()
    {
        return _expression_;
    }

    public void setExpression(PExpression node)
    {
        if(_expression_ != null)
        {
            _expression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _expression_ = node;
    }

    public LinkedList getArglist()
    {
        return _arglist_;
    }

    public void setArglist(List list)
    {
        _arglist_.clear();
        _arglist_.addAll(list);
    }

    public String toString()
    {
        return ""
            + toString(_expression_)
            + toString(_arglist_);
    }

    void removeChild(Node child)
    {
        if(_expression_ == child)
        {
            _expression_ = null;
            return;
        }

        if(_arglist_.remove(child))
        {
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_expression_ == oldChild)
        {
            setExpression((PExpression) newChild);
            return;
        }

        for(ListIterator i = _arglist_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

    }

    private class Arglist_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PArglist node = (PArglist) o;

            if((node.parent() != null) &&
                (node.parent() != AFunctionCall.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != AFunctionCall.this))
            {
                node.parent(AFunctionCall.this);
            }

            return node;
        }
    }
}
