/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AMinusExpression extends PExpression
{
    private PExpression _lExp_;
    private PExpression _rExp_;

    public AMinusExpression()
    {
    }

    public AMinusExpression(
        PExpression _lExp_,
        PExpression _rExp_)
    {
        setLExp(_lExp_);

        setRExp(_rExp_);

    }
    public Object clone()
    {
        return new AMinusExpression(
            (PExpression) cloneNode(_lExp_),
            (PExpression) cloneNode(_rExp_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMinusExpression(this);
    }

    public PExpression getLExp()
    {
        return _lExp_;
    }

    public void setLExp(PExpression node)
    {
        if(_lExp_ != null)
        {
            _lExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _lExp_ = node;
    }

    public PExpression getRExp()
    {
        return _rExp_;
    }

    public void setRExp(PExpression node)
    {
        if(_rExp_ != null)
        {
            _rExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _rExp_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_lExp_)
            + toString(_rExp_);
    }

    void removeChild(Node child)
    {
        if(_lExp_ == child)
        {
            _lExp_ = null;
            return;
        }

        if(_rExp_ == child)
        {
            _rExp_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_lExp_ == oldChild)
        {
            setLExp((PExpression) newChild);
            return;
        }

        if(_rExp_ == oldChild)
        {
            setRExp((PExpression) newChild);
            return;
        }

    }
}
