/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AOrcComparison extends PComparison
{
    private PComparison _lComp_;
    private PComparison _rCompa_;

    public AOrcComparison()
    {
    }

    public AOrcComparison(
        PComparison _lComp_,
        PComparison _rCompa_)
    {
        setLComp(_lComp_);

        setRCompa(_rCompa_);

    }
    public Object clone()
    {
        return new AOrcComparison(
            (PComparison) cloneNode(_lComp_),
            (PComparison) cloneNode(_rCompa_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOrcComparison(this);
    }

    public PComparison getLComp()
    {
        return _lComp_;
    }

    public void setLComp(PComparison node)
    {
        if(_lComp_ != null)
        {
            _lComp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _lComp_ = node;
    }

    public PComparison getRCompa()
    {
        return _rCompa_;
    }

    public void setRCompa(PComparison node)
    {
        if(_rCompa_ != null)
        {
            _rCompa_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _rCompa_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_lComp_)
            + toString(_rCompa_);
    }

    void removeChild(Node child)
    {
        if(_lComp_ == child)
        {
            _lComp_ = null;
            return;
        }

        if(_rCompa_ == child)
        {
            _rCompa_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_lComp_ == oldChild)
        {
            setLComp((PComparison) newChild);
            return;
        }

        if(_rCompa_ == oldChild)
        {
            setRCompa((PComparison) newChild);
            return;
        }

    }
}
