/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

public final class TClassToken extends Token
{
    public TClassToken()
    {
        super.setText("class");
    }

    public TClassToken(int line, int pos)
    {
        super.setText("class");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TClassToken(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTClassToken(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TClassToken text.");
    }
}
