/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

public final class TEqeq extends Token
{
    public TEqeq()
    {
        super.setText("==");
    }

    public TEqeq(int line, int pos)
    {
        super.setText("==");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TEqeq(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTEqeq(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TEqeq text.");
    }
}
