/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

public final class TLSqBrack extends Token
{
    public TLSqBrack()
    {
        super.setText("[");
    }

    public TLSqBrack(int line, int pos)
    {
        super.setText("[");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TLSqBrack(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTLSqBrack(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TLSqBrack text.");
    }
}
