/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

public final class TRSqBrack extends Token
{
    public TRSqBrack()
    {
        super.setText("]");
    }

    public TRSqBrack(int line, int pos)
    {
        super.setText("]");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TRSqBrack(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTRSqBrack(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TRSqBrack text.");
    }
}
