/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

public final class TSinquote extends Token
{
    public TSinquote()
    {
        super.setText("\'");
    }

    public TSinquote(int line, int pos)
    {
        super.setText("\'");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TSinquote(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSinquote(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TSinquote text.");
    }
}
