/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.parser;

import minipython.lexer.*;
import minipython.node.*;
import minipython.analysis.*;
import java.util.*;

import java.io.DataInputStream;
import java.io.BufferedInputStream;
import java.io.IOException;

public class Parser
{
    public final Analysis ignoredTokens = new AnalysisAdapter();

    protected ArrayList nodeList;

    private final Lexer lexer;
    private final ListIterator stack = new LinkedList().listIterator();
    private int last_shift;
    private int last_pos;
    private int last_line;
    private Token last_token;
    private final TokenIndex converter = new TokenIndex();
    private final int[] action = new int[2];

    private final static int SHIFT = 0;
    private final static int REDUCE = 1;
    private final static int ACCEPT = 2;
    private final static int ERROR = 3;

    public Parser(Lexer lexer)
    {
        this.lexer = lexer;

        if(actionTable == null)
        {
            try
            {
                DataInputStream s = new DataInputStream(
                    new BufferedInputStream(
                    Parser.class.getResourceAsStream("parser.dat")));

                // read actionTable
                int length = s.readInt();
                actionTable = new int[length][][];
                for(int i = 0; i < actionTable.length; i++)
                {
                    length = s.readInt();
                    actionTable[i] = new int[length][3];
                    for(int j = 0; j < actionTable[i].length; j++)
                    {
                        for(int k = 0; k < 3; k++)
                        {
                            actionTable[i][j][k] = s.readInt();
                        }
                    }
                }

                // read gotoTable
                length = s.readInt();
                gotoTable = new int[length][][];
                for(int i = 0; i < gotoTable.length; i++)
                {
                    length = s.readInt();
                    gotoTable[i] = new int[length][2];
                    for(int j = 0; j < gotoTable[i].length; j++)
                    {
                        for(int k = 0; k < 2; k++)
                        {
                            gotoTable[i][j][k] = s.readInt();
                        }
                    }
                }

                // read errorMessages
                length = s.readInt();
                errorMessages = new String[length];
                for(int i = 0; i < errorMessages.length; i++)
                {
                    length = s.readInt();
                    StringBuffer buffer = new StringBuffer();

                    for(int j = 0; j < length; j++)
                    {
                        buffer.append(s.readChar());
                    }
                    errorMessages[i] = buffer.toString();
                }

                // read errors
                length = s.readInt();
                errors = new int[length];
                for(int i = 0; i < errors.length; i++)
                {
                    errors[i] = s.readInt();
                }

                s.close();
            }
            catch(Exception e)
            {
                throw new RuntimeException("The file \"parser.dat\" is either missing or corrupted.");
            }
        }
    }

    private int goTo(int index)
    {
        int state = state();
        int low = 1;
        int high = gotoTable[index].length - 1;
        int value = gotoTable[index][0][1];

        while(low <= high)
        {
            int middle = (low + high) / 2;

            if(state < gotoTable[index][middle][0])
            {
                high = middle - 1;
            }
            else if(state > gotoTable[index][middle][0])
            {
                low = middle + 1;
            }
            else
            {
                value = gotoTable[index][middle][1];
                break;
            }
        }

        return value;
    }

    private void push(int numstate, ArrayList listNode) throws ParserException, LexerException, IOException
    {
	this.nodeList = listNode;

        if(!stack.hasNext())
        {
            stack.add(new State(numstate, this.nodeList));
            return;
        }

        State s = (State) stack.next();
        s.state = numstate;
        s.nodes = this.nodeList;
    }

    private int state()
    {
        State s = (State) stack.previous();
        stack.next();
        return s.state;
    }

    private ArrayList pop()
    {
        return (ArrayList) ((State) stack.previous()).nodes;
    }

    private int index(Switchable token)
    {
        converter.index = -1;
        token.apply(converter);
        return converter.index;
    }

    public Start parse() throws ParserException, LexerException, IOException
    {
        push(0, null);

        List ign = null;
        while(true)
        {
            while(index(lexer.peek()) == -1)
            {
                if(ign == null)
                {
                    ign = new TypedLinkedList(NodeCast.instance);
                }

                ign.add(lexer.next());
            }

            if(ign != null)
            {
                ignoredTokens.setIn(lexer.peek(), ign);
                ign = null;
            }

            last_pos = lexer.peek().getPos();
            last_line = lexer.peek().getLine();
            last_token = lexer.peek();

            int index = index(lexer.peek());
            action[0] = actionTable[state()][0][1];
            action[1] = actionTable[state()][0][2];

            int low = 1;
            int high = actionTable[state()].length - 1;

            while(low <= high)
            {
                int middle = (low + high) / 2;

                if(index < actionTable[state()][middle][0])
                {
                    high = middle - 1;
                }
                else if(index > actionTable[state()][middle][0])
                {
                    low = middle + 1;
                }
                else
                {
                    action[0] = actionTable[state()][middle][1];
                    action[1] = actionTable[state()][middle][2];
                    break;
                }
            }

            switch(action[0])
            {
                case SHIFT:
		    {
		        ArrayList list = new ArrayList();
		        list.add(lexer.next());
                        push(action[1], list);
                        last_shift = action[1];
                    }
		    break;
                case REDUCE:
                    switch(action[1])
                    {

                    case 0:
		    {
			ArrayList list = new0();
			push(goTo(0), list);
		    }
		    break;


                    case 1:
		    {
			ArrayList list = new1();
			push(goTo(0), list);
		    }
		    break;


                    case 2:
		    {
			ArrayList list = new2();
			push(goTo(1), list);
		    }
		    break;


                    case 3:
		    {
			ArrayList list = new3();
			push(goTo(1), list);
		    }
		    break;


                    case 4:
		    {
			ArrayList list = new4();
			push(goTo(2), list);
		    }
		    break;


                    case 5:
		    {
			ArrayList list = new5();
			push(goTo(2), list);
		    }
		    break;


                    case 6:
		    {
			ArrayList list = new6();
			push(goTo(3), list);
		    }
		    break;


                    case 7:
		    {
			ArrayList list = new7();
			push(goTo(3), list);
		    }
		    break;


                    case 8:
		    {
			ArrayList list = new8();
			push(goTo(3), list);
		    }
		    break;


                    case 9:
		    {
			ArrayList list = new9();
			push(goTo(3), list);
		    }
		    break;


                    case 10:
		    {
			ArrayList list = new10();
			push(goTo(4), list);
		    }
		    break;


                    case 11:
		    {
			ArrayList list = new11();
			push(goTo(4), list);
		    }
		    break;


                    case 12:
		    {
			ArrayList list = new12();
			push(goTo(4), list);
		    }
		    break;


                    case 13:
		    {
			ArrayList list = new13();
			push(goTo(4), list);
		    }
		    break;


                    case 14:
		    {
			ArrayList list = new14();
			push(goTo(4), list);
		    }
		    break;


                    case 15:
		    {
			ArrayList list = new15();
			push(goTo(4), list);
		    }
		    break;


                    case 16:
		    {
			ArrayList list = new16();
			push(goTo(4), list);
		    }
		    break;


                    case 17:
		    {
			ArrayList list = new17();
			push(goTo(4), list);
		    }
		    break;


                    case 18:
		    {
			ArrayList list = new18();
			push(goTo(4), list);
		    }
		    break;


                    case 19:
		    {
			ArrayList list = new19();
			push(goTo(4), list);
		    }
		    break;


                    case 20:
		    {
			ArrayList list = new20();
			push(goTo(4), list);
		    }
		    break;


                    case 21:
		    {
			ArrayList list = new21();
			push(goTo(4), list);
		    }
		    break;


                    case 22:
		    {
			ArrayList list = new22();
			push(goTo(4), list);
		    }
		    break;


                    case 23:
		    {
			ArrayList list = new23();
			push(goTo(4), list);
		    }
		    break;


                    case 24:
		    {
			ArrayList list = new24();
			push(goTo(4), list);
		    }
		    break;


                    case 25:
		    {
			ArrayList list = new25();
			push(goTo(4), list);
		    }
		    break;


                    case 26:
		    {
			ArrayList list = new26();
			push(goTo(4), list);
		    }
		    break;


                    case 27:
		    {
			ArrayList list = new27();
			push(goTo(4), list);
		    }
		    break;


                    case 28:
		    {
			ArrayList list = new28();
			push(goTo(4), list);
		    }
		    break;


                    case 29:
		    {
			ArrayList list = new29();
			push(goTo(4), list);
		    }
		    break;


                    case 30:
		    {
			ArrayList list = new30();
			push(goTo(4), list);
		    }
		    break;


                    case 31:
		    {
			ArrayList list = new31();
			push(goTo(4), list);
		    }
		    break;


                    case 32:
		    {
			ArrayList list = new32();
			push(goTo(4), list);
		    }
		    break;


                    case 33:
		    {
			ArrayList list = new33();
			push(goTo(4), list);
		    }
		    break;


                    case 34:
		    {
			ArrayList list = new34();
			push(goTo(4), list);
		    }
		    break;


                    case 35:
		    {
			ArrayList list = new35();
			push(goTo(4), list);
		    }
		    break;


                    case 36:
		    {
			ArrayList list = new36();
			push(goTo(5), list);
		    }
		    break;


                    case 37:
		    {
			ArrayList list = new37();
			push(goTo(5), list);
		    }
		    break;


                    case 38:
		    {
			ArrayList list = new38();
			push(goTo(6), list);
		    }
		    break;


                    case 39:
		    {
			ArrayList list = new39();
			push(goTo(6), list);
		    }
		    break;


                    case 40:
		    {
			ArrayList list = new40();
			push(goTo(7), list);
		    }
		    break;


                    case 41:
		    {
			ArrayList list = new41();
			push(goTo(7), list);
		    }
		    break;


                    case 42:
		    {
			ArrayList list = new42();
			push(goTo(8), list);
		    }
		    break;


                    case 43:
		    {
			ArrayList list = new43();
			push(goTo(8), list);
		    }
		    break;


                    case 44:
		    {
			ArrayList list = new44();
			push(goTo(8), list);
		    }
		    break;


                    case 45:
		    {
			ArrayList list = new45();
			push(goTo(8), list);
		    }
		    break;


                    case 46:
		    {
			ArrayList list = new46();
			push(goTo(8), list);
		    }
		    break;


                    case 47:
		    {
			ArrayList list = new47();
			push(goTo(8), list);
		    }
		    break;


                    case 48:
		    {
			ArrayList list = new48();
			push(goTo(8), list);
		    }
		    break;


                    case 49:
		    {
			ArrayList list = new49();
			push(goTo(8), list);
		    }
		    break;


                    case 50:
		    {
			ArrayList list = new50();
			push(goTo(9), list);
		    }
		    break;


                    case 51:
		    {
			ArrayList list = new51();
			push(goTo(9), list);
		    }
		    break;


                    case 52:
		    {
			ArrayList list = new52();
			push(goTo(9), list);
		    }
		    break;


                    case 53:
		    {
			ArrayList list = new53();
			push(goTo(10), list);
		    }
		    break;


                    case 54:
		    {
			ArrayList list = new54();
			push(goTo(10), list);
		    }
		    break;


                    case 55:
		    {
			ArrayList list = new55();
			push(goTo(10), list);
		    }
		    break;


                    case 56:
		    {
			ArrayList list = new56();
			push(goTo(10), list);
		    }
		    break;


                    case 57:
		    {
			ArrayList list = new57();
			push(goTo(11), list);
		    }
		    break;


                    case 58:
		    {
			ArrayList list = new58();
			push(goTo(11), list);
		    }
		    break;


                    case 59:
		    {
			ArrayList list = new59();
			push(goTo(12), list);
		    }
		    break;


                    case 60:
		    {
			ArrayList list = new60();
			push(goTo(12), list);
		    }
		    break;


                    case 61:
		    {
			ArrayList list = new61();
			push(goTo(12), list);
		    }
		    break;


                    case 62:
		    {
			ArrayList list = new62();
			push(goTo(12), list);
		    }
		    break;


                    case 63:
		    {
			ArrayList list = new63();
			push(goTo(12), list);
		    }
		    break;


                    case 64:
		    {
			ArrayList list = new64();
			push(goTo(12), list);
		    }
		    break;


                    case 65:
		    {
			ArrayList list = new65();
			push(goTo(12), list);
		    }
		    break;


                    case 66:
		    {
			ArrayList list = new66();
			push(goTo(12), list);
		    }
		    break;


                    case 67:
		    {
			ArrayList list = new67();
			push(goTo(12), list);
		    }
		    break;


                    case 68:
		    {
			ArrayList list = new68();
			push(goTo(12), list);
		    }
		    break;


                    case 69:
		    {
			ArrayList list = new69();
			push(goTo(12), list);
		    }
		    break;


                    case 70:
		    {
			ArrayList list = new70();
			push(goTo(12), list);
		    }
		    break;


                    case 71:
		    {
			ArrayList list = new71();
			push(goTo(12), list);
		    }
		    break;


                    case 72:
		    {
			ArrayList list = new72();
			push(goTo(12), list);
		    }
		    break;


                    case 73:
		    {
			ArrayList list = new73();
			push(goTo(13), list);
		    }
		    break;


                    case 74:
		    {
			ArrayList list = new74();
			push(goTo(13), list);
		    }
		    break;


                    case 75:
		    {
			ArrayList list = new75();
			push(goTo(14), list);
		    }
		    break;


                    case 76:
		    {
			ArrayList list = new76();
			push(goTo(14), list);
		    }
		    break;


                    case 77:
		    {
			ArrayList list = new77();
			push(goTo(15), list);
		    }
		    break;


                    case 78:
		    {
			ArrayList list = new78();
			push(goTo(15), list);
		    }
		    break;


                    case 79:
		    {
			ArrayList list = new79();
			push(goTo(15), list);
		    }
		    break;


                    case 80:
		    {
			ArrayList list = new80();
			push(goTo(15), list);
		    }
		    break;


                    case 81:
		    {
			ArrayList list = new81();
			push(goTo(16), list);
		    }
		    break;


                    case 82:
		    {
			ArrayList list = new82();
			push(goTo(17), list);
		    }
		    break;


                    case 83:
		    {
			ArrayList list = new83();
			push(goTo(18), list);
		    }
		    break;


                    case 84:
		    {
			ArrayList list = new84();
			push(goTo(19), list);
		    }
		    break;


                    case 85:
		    {
			ArrayList list = new85();
			push(goTo(20), list);
		    }
		    break;


                    case 86:
		    {
			ArrayList list = new86();
			push(goTo(20), list);
		    }
		    break;


                    case 87:
		    {
			ArrayList list = new87();
			push(goTo(21), list);
		    }
		    break;


                    case 88:
		    {
			ArrayList list = new88();
			push(goTo(21), list);
		    }
		    break;


                    case 89:
		    {
			ArrayList list = new89();
			push(goTo(22), list);
		    }
		    break;


                    case 90:
		    {
			ArrayList list = new90();
			push(goTo(22), list);
		    }
		    break;


                    case 91:
		    {
			ArrayList list = new91();
			push(goTo(23), list);
		    }
		    break;


                    case 92:
		    {
			ArrayList list = new92();
			push(goTo(23), list);
		    }
		    break;


                    case 93:
		    {
			ArrayList list = new93();
			push(goTo(24), list);
		    }
		    break;


                    case 94:
		    {
			ArrayList list = new94();
			push(goTo(24), list);
		    }
		    break;


                    case 95:
		    {
			ArrayList list = new95();
			push(goTo(25), list);
		    }
		    break;


                    case 96:
		    {
			ArrayList list = new96();
			push(goTo(25), list);
		    }
		    break;

                    }
                    break;
                case ACCEPT:
                    {
                        EOF node2 = (EOF) lexer.next();
                        PProgramme node1 = (PProgramme) ((ArrayList)pop()).get(0);
                        Start node = new Start(node1, node2);
                        return node;
                    }
                case ERROR:
                    throw new ParserException(last_token,
                        "[" + last_line + "," + last_pos + "] " +
                        errorMessages[errors[action[1]]]);
            }
        }
    }



    ArrayList new0()
    {
        ArrayList nodeList = new ArrayList();

        PProgramme pprogrammeNode1;
        {
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        }

        pprogrammeNode1 = new AProgramme(listNode2);
        }
	nodeList.add(pprogrammeNode1);
        return nodeList;
    }



    ArrayList new1()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PProgramme pprogrammeNode1;
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode2 = new TypedLinkedList();
        listNode2 = (TypedLinkedList)nodeArrayList1.get(0);
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }

        pprogrammeNode1 = new AProgramme(listNode3);
        }
	nodeList.add(pprogrammeNode1);
        return nodeList;
    }



    ArrayList new2()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PCommands pcommandsNode1;
        {
        PStatement pstatementNode2;
        pstatementNode2 = (PStatement)nodeArrayList1.get(0);

        pcommandsNode1 = new AStatCommands(pstatementNode2);
        }
	nodeList.add(pcommandsNode1);
        return nodeList;
    }



    ArrayList new3()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PCommands pcommandsNode1;
        {
        PFunction pfunctionNode2;
        pfunctionNode2 = (PFunction)nodeArrayList1.get(0);

        pcommandsNode1 = new AFunctCommands(pfunctionNode2);
        }
	nodeList.add(pcommandsNode1);
        return nodeList;
    }



    ArrayList new4()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PFunction pfunctionNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode3 = new TypedLinkedList();
        PStatement pstatementNode4;
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);
        {
        }
        pstatementNode4 = (PStatement)nodeArrayList6.get(0);

        pfunctionNode1 = new AFunction(pexpressionNode2, listNode3, pstatementNode4);
        }
	nodeList.add(pfunctionNode1);
        return nodeList;
    }



    ArrayList new5()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList7 = (ArrayList) pop();
        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PFunction pfunctionNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        PStatement pstatementNode5;
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);
        {
        PArgument pargumentNode3;
        pargumentNode3 = (PArgument)nodeArrayList4.get(0);
	if(pargumentNode3 != null)
	{
	  listNode4.add(pargumentNode3);
	}
        }
        pstatementNode5 = (PStatement)nodeArrayList7.get(0);

        pfunctionNode1 = new AFunction(pexpressionNode2, listNode4, pstatementNode5);
        }
	nodeList.add(pfunctionNode1);
        return nodeList;
    }



    ArrayList new6()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PArgument pargumentNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode3 = new TypedLinkedList();
        TypedLinkedList listNode4 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        {
        }
        {
        }

        pargumentNode1 = new AArgument(pexpressionNode2, listNode3, listNode4);
        }
	nodeList.add(pargumentNode1);
        return nodeList;
    }



    ArrayList new7()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PArgument pargumentNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        TypedLinkedList listNode5 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        {
        PEqVal peqvalNode3;
        peqvalNode3 = (PEqVal)nodeArrayList2.get(0);
	if(peqvalNode3 != null)
	{
	  listNode4.add(peqvalNode3);
	}
        }
        {
        }

        pargumentNode1 = new AArgument(pexpressionNode2, listNode4, listNode5);
        }
	nodeList.add(pargumentNode1);
        return nodeList;
    }



    ArrayList new8()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PArgument pargumentNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode3 = new TypedLinkedList();
        TypedLinkedList listNode5 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        {
        }
        {
        TypedLinkedList listNode4 = new TypedLinkedList();
        listNode4 = (TypedLinkedList)nodeArrayList2.get(0);
	if(listNode4 != null)
	{
	  listNode5.addAll(listNode4);
	}
        }

        pargumentNode1 = new AArgument(pexpressionNode2, listNode3, listNode5);
        }
	nodeList.add(pargumentNode1);
        return nodeList;
    }



    ArrayList new9()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PArgument pargumentNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        TypedLinkedList listNode6 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        {
        PEqVal peqvalNode3;
        peqvalNode3 = (PEqVal)nodeArrayList2.get(0);
	if(peqvalNode3 != null)
	{
	  listNode4.add(peqvalNode3);
	}
        }
        {
        TypedLinkedList listNode5 = new TypedLinkedList();
        listNode5 = (TypedLinkedList)nodeArrayList3.get(0);
	if(listNode5 != null)
	{
	  listNode6.addAll(listNode5);
	}
        }

        pargumentNode1 = new AArgument(pexpressionNode2, listNode4, listNode6);
        }
	nodeList.add(pargumentNode1);
        return nodeList;
    }



    ArrayList new10()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PComparison pcomparisonNode2;
        PStatement pstatementNode3;
        pcomparisonNode2 = (PComparison)nodeArrayList2.get(0);
        pstatementNode3 = (PStatement)nodeArrayList4.get(0);

        pstatementNode1 = new AIfStmtStatement(pcomparisonNode2, pstatementNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new11()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PComparison pcomparisonNode2;
        PStatement pstatementNode3;
        pcomparisonNode2 = (PComparison)nodeArrayList3.get(0);
        pstatementNode3 = (PStatement)nodeArrayList5.get(0);

        pstatementNode1 = new AIfStmtStatement(pcomparisonNode2, pstatementNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new12()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PComparison pcomparisonNode2;
        PStatement pstatementNode3;
        pcomparisonNode2 = (PComparison)nodeArrayList2.get(0);
        pstatementNode3 = (PStatement)nodeArrayList4.get(0);

        pstatementNode1 = new AWhileStmtStatement(pcomparisonNode2, pstatementNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new13()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PComparison pcomparisonNode2;
        PStatement pstatementNode3;
        pcomparisonNode2 = (PComparison)nodeArrayList3.get(0);
        pstatementNode3 = (PStatement)nodeArrayList5.get(0);

        pstatementNode1 = new AWhileStmtStatement(pcomparisonNode2, pstatementNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new14()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        PStatement pstatementNode4;
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList4.get(0);
        pstatementNode4 = (PStatement)nodeArrayList6.get(0);

        pstatementNode1 = new AForStmtStatement(pexpressionNode2, pexpressionNode3, pstatementNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new15()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList7 = (ArrayList) pop();
        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        PStatement pstatementNode4;
        pexpressionNode2 = (PExpression)nodeArrayList3.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList5.get(0);
        pstatementNode4 = (PStatement)nodeArrayList7.get(0);

        pstatementNode1 = new AForStmtStatement(pexpressionNode2, pexpressionNode3, pstatementNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new16()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);

        pstatementNode1 = new AReturnStmtStatement(pexpressionNode2);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new17()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        pexpressionNode2 = (PExpression)nodeArrayList3.get(0);

        pstatementNode1 = new AReturnStmtStatement(pexpressionNode2);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new18()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode3 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);
        {
        }

        pstatementNode1 = new APrintStmtStatement(pexpressionNode2, listNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new19()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode3 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList3.get(0);
        {
        }

        pstatementNode1 = new APrintStmtStatement(pexpressionNode2, listNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new20()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        listNode3 = (TypedLinkedList)nodeArrayList3.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }

        pstatementNode1 = new APrintStmtStatement(pexpressionNode2, listNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new21()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList3.get(0);
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        listNode3 = (TypedLinkedList)nodeArrayList4.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }

        pstatementNode1 = new APrintStmtStatement(pexpressionNode2, listNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new22()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pstatementNode1 = new AEqStmtStatement(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new23()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList4.get(0);

        pstatementNode1 = new AEqStmtStatement(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new24()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pstatementNode1 = new AMineqStmtStatement(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new25()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList4.get(0);

        pstatementNode1 = new AMineqStmtStatement(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new26()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pstatementNode1 = new ADiveqStmtStatement(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new27()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList4.get(0);

        pstatementNode1 = new ADiveqStmtStatement(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new28()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        PExpression pexpressionNode4;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);
        pexpressionNode4 = (PExpression)nodeArrayList6.get(0);

        pstatementNode1 = new AArrayStmtStatement(pexpressionNode2, pexpressionNode3, pexpressionNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new29()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList7 = (ArrayList) pop();
        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        PExpression pexpressionNode4;
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList4.get(0);
        pexpressionNode4 = (PExpression)nodeArrayList7.get(0);

        pstatementNode1 = new AArrayStmtStatement(pexpressionNode2, pexpressionNode3, pexpressionNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new30()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode3 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);
        {
        }

        pstatementNode1 = new AAssertStmtStatement(pexpressionNode2, listNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new31()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode3 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList3.get(0);
        {
        }

        pstatementNode1 = new AAssertStmtStatement(pexpressionNode2, listNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new32()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);
        {
        PExpression pexpressionNode3;
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);
	if(pexpressionNode3 != null)
	{
	  listNode4.add(pexpressionNode3);
	}
        }

        pstatementNode1 = new AAssertStmtStatement(pexpressionNode2, listNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new33()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList3.get(0);
        {
        PExpression pexpressionNode3;
        pexpressionNode3 = (PExpression)nodeArrayList4.get(0);
	if(pexpressionNode3 != null)
	{
	  listNode4.add(pexpressionNode3);
	}
        }

        pstatementNode1 = new AAssertStmtStatement(pexpressionNode2, listNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new34()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PFunctionCall pfunctioncallNode2;
        pfunctioncallNode2 = (PFunctionCall)nodeArrayList1.get(0);

        pstatementNode1 = new AFunccallStmtStatement(pfunctioncallNode2);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new35()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PFunctionCall pfunctioncallNode2;
        pfunctioncallNode2 = (PFunctionCall)nodeArrayList2.get(0);

        pstatementNode1 = new AFunccallStmtStatement(pfunctioncallNode2);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new36()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        pcomparisonNode1 = (PComparison)nodeArrayList1.get(0);
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new37()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        {
        PComparison pcomparisonNode2;
        PComparison pcomparisonNode3;
        pcomparisonNode2 = (PComparison)nodeArrayList1.get(0);
        pcomparisonNode3 = (PComparison)nodeArrayList3.get(0);

        pcomparisonNode1 = new AOrcComparison(pcomparisonNode2, pcomparisonNode3);
        }
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new38()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        pcomparisonNode1 = (PComparison)nodeArrayList1.get(0);
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new39()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        {
        PComparison pcomparisonNode2;
        PComparison pcomparisonNode3;
        pcomparisonNode2 = (PComparison)nodeArrayList1.get(0);
        pcomparisonNode3 = (PComparison)nodeArrayList3.get(0);

        pcomparisonNode1 = new AAndComparisonComparison(pcomparisonNode2, pcomparisonNode3);
        }
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new40()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        {
        PComparison pcomparisonNode2;
        pcomparisonNode2 = (PComparison)nodeArrayList2.get(0);

        pcomparisonNode1 = new ANotcComparison(pcomparisonNode2);
        }
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new41()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        pcomparisonNode1 = (PComparison)nodeArrayList1.get(0);
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new42()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pcomparisonNode1 = new AGreatcComparison(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new43()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pcomparisonNode1 = new ALesscComparison(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new44()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pcomparisonNode1 = new AGreateqcComparison(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new45()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pcomparisonNode1 = new ALesseqcComparison(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new46()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pcomparisonNode1 = new ANoteqcComparison(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new47()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pcomparisonNode1 = new AEqcComparison(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new48()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        {

        pcomparisonNode1 = new ATrueComparison();
        }
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new49()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        {

        pcomparisonNode1 = new AFalseComparison();
        }
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new50()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        pexpressionNode1 = (PExpression)nodeArrayList1.get(0);
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new51()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new AAddExpression(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new52()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new AMinusExpression(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new53()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        pexpressionNode1 = (PExpression)nodeArrayList1.get(0);
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new54()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new AMultiplicationExpression(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new55()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new ADivisionExpression(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new56()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new AModulusExpression(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new57()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        pexpressionNode1 = (PExpression)nodeArrayList1.get(0);
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new58()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new AExponExpression(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new59()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new AArrayExpression(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new60()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PFunctionCall pfunctioncallNode2;
        pfunctioncallNode2 = (PFunctionCall)nodeArrayList1.get(0);

        pexpressionNode1 = new AFuncExpression(pfunctioncallNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new61()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        pexpressionNode1 = (PExpression)nodeArrayList1.get(0);
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new62()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        pexpressionNode1 = (PExpression)nodeArrayList1.get(0);
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new63()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);

        pexpressionNode1 = new APlusplusExpression(pexpressionNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new64()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);

        pexpressionNode1 = new AMinminExpression(pexpressionNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new65()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        pexpressionNode2 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new ALenExpression(pexpressionNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new66()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode3 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList3.get(0);
        {
        }

        pexpressionNode1 = new AMaxExpression(pexpressionNode2, listNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new67()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList3.get(0);
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        listNode3 = (TypedLinkedList)nodeArrayList4.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }

        pexpressionNode1 = new AMaxExpression(pexpressionNode2, listNode4);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new68()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode3 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList3.get(0);
        {
        }

        pexpressionNode1 = new AMinExpression(pexpressionNode2, listNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new69()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList3.get(0);
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        listNode3 = (TypedLinkedList)nodeArrayList4.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }

        pexpressionNode1 = new AMinExpression(pexpressionNode2, listNode4);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new70()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        pexpressionNode1 = (PExpression)nodeArrayList2.get(0);
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new71()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode3 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);
        {
        }

        pexpressionNode1 = new ASqbrExpression(pexpressionNode2, listNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new72()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        listNode3 = (TypedLinkedList)nodeArrayList3.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }

        pexpressionNode1 = new ASqbrExpression(pexpressionNode2, listNode4);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new73()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PFunctionCall pfunctioncallNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode3 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        {
        }

        pfunctioncallNode1 = new AFunctionCall(pexpressionNode2, listNode3);
        }
	nodeList.add(pfunctioncallNode1);
        return nodeList;
    }



    ArrayList new74()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PFunctionCall pfunctioncallNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        {
        PArglist parglistNode3;
        parglistNode3 = (PArglist)nodeArrayList3.get(0);
	if(parglistNode3 != null)
	{
	  listNode4.add(parglistNode3);
	}
        }

        pfunctioncallNode1 = new AFunctionCall(pexpressionNode2, listNode4);
        }
	nodeList.add(pfunctioncallNode1);
        return nodeList;
    }



    ArrayList new75()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PArglist parglistNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode3 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        {
        }

        parglistNode1 = new AArglist(pexpressionNode2, listNode3);
        }
	nodeList.add(parglistNode1);
        return nodeList;
    }



    ArrayList new76()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PArglist parglistNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        listNode3 = (TypedLinkedList)nodeArrayList2.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }

        parglistNode1 = new AArglist(pexpressionNode2, listNode4);
        }
	nodeList.add(parglistNode1);
        return nodeList;
    }



    ArrayList new77()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        PFunctionCall pfunctioncallNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pfunctioncallNode3 = (PFunctionCall)nodeArrayList3.get(0);

        pexpressionNode1 = new AFunccallExpression(pexpressionNode2, pfunctioncallNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new78()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        TNumber tnumberNode2;
        tnumberNode2 = (TNumber)nodeArrayList1.get(0);

        pexpressionNode1 = new ANumExpression(tnumberNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new79()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        TString tstringNode2;
        tstringNode2 = (TString)nodeArrayList1.get(0);

        pexpressionNode1 = new AStrExpression(tstringNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new80()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        TNone tnoneNode2;
        tnoneNode2 = (TNone)nodeArrayList1.get(0);

        pexpressionNode1 = new ANoneExpression(tnoneNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new81()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        TId tidNode2;
        tidNode2 = (TId)nodeArrayList1.get(0);

        pexpressionNode1 = new AIdentExpression(tidNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new82()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        pexpressionNode1 = (PExpression)nodeArrayList2.get(0);
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new83()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        pexpressionNode1 = (PExpression)nodeArrayList2.get(0);
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new84()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PEqVal peqvalNode1;
        {
        PExpression pexpressionNode2;
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);

        peqvalNode1 = new AEqVal(pexpressionNode2);
        }
	nodeList.add(peqvalNode1);
        return nodeList;
    }



    ArrayList new85()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PArgumentHelper pargumenthelperNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode3 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);
        {
        }

        pargumenthelperNode1 = new AArgumentHelper(pexpressionNode2, listNode3);
        }
	nodeList.add(pargumenthelperNode1);
        return nodeList;
    }



    ArrayList new86()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PArgumentHelper pargumenthelperNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);
        {
        PEqVal peqvalNode3;
        peqvalNode3 = (PEqVal)nodeArrayList3.get(0);
	if(peqvalNode3 != null)
	{
	  listNode4.add(peqvalNode3);
	}
        }

        pargumenthelperNode1 = new AArgumentHelper(pexpressionNode2, listNode4);
        }
	nodeList.add(pargumenthelperNode1);
        return nodeList;
    }



    ArrayList new87()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        PCommands pcommandsNode1;
        pcommandsNode1 = (PCommands)nodeArrayList1.get(0);
	if(pcommandsNode1 != null)
	{
	  listNode2.add(pcommandsNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    ArrayList new88()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode1 = new TypedLinkedList();
        PCommands pcommandsNode2;
        listNode1 = (TypedLinkedList)nodeArrayList1.get(0);
        pcommandsNode2 = (PCommands)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pcommandsNode2 != null)
	{
	  listNode3.add(pcommandsNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    ArrayList new89()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        PArgumentHelper pargumenthelperNode1;
        pargumenthelperNode1 = (PArgumentHelper)nodeArrayList1.get(0);
	if(pargumenthelperNode1 != null)
	{
	  listNode2.add(pargumenthelperNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    ArrayList new90()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode1 = new TypedLinkedList();
        PArgumentHelper pargumenthelperNode2;
        listNode1 = (TypedLinkedList)nodeArrayList1.get(0);
        pargumenthelperNode2 = (PArgumentHelper)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pargumenthelperNode2 != null)
	{
	  listNode3.add(pargumenthelperNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    ArrayList new91()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        TTab ttabNode1;
        ttabNode1 = (TTab)nodeArrayList1.get(0);
	if(ttabNode1 != null)
	{
	  listNode2.add(ttabNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    ArrayList new92()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode1 = new TypedLinkedList();
        TTab ttabNode2;
        listNode1 = (TypedLinkedList)nodeArrayList1.get(0);
        ttabNode2 = (TTab)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(ttabNode2 != null)
	{
	  listNode3.add(ttabNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    ArrayList new93()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        PExpression pexpressionNode1;
        pexpressionNode1 = (PExpression)nodeArrayList1.get(0);
	if(pexpressionNode1 != null)
	{
	  listNode2.add(pexpressionNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    ArrayList new94()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode1 = new TypedLinkedList();
        PExpression pexpressionNode2;
        listNode1 = (TypedLinkedList)nodeArrayList1.get(0);
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pexpressionNode2 != null)
	{
	  listNode3.add(pexpressionNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    ArrayList new95()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        PExpression pexpressionNode1;
        pexpressionNode1 = (PExpression)nodeArrayList1.get(0);
	if(pexpressionNode1 != null)
	{
	  listNode2.add(pexpressionNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    ArrayList new96()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode1 = new TypedLinkedList();
        PExpression pexpressionNode2;
        listNode1 = (TypedLinkedList)nodeArrayList1.get(0);
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pexpressionNode2 != null)
	{
	  listNode3.add(pexpressionNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    private static int[][][] actionTable;
/*      {
			{{-1, REDUCE, 0}, {0, SHIFT, 1}, {3, SHIFT, 2}, {28, SHIFT, 3}, {38, SHIFT, 4}, {41, SHIFT, 5}, {43, SHIFT, 6}, {44, SHIFT, 7}, {45, SHIFT, 8}, {54, SHIFT, 9}, },
			{{-1, REDUCE, 91}, },
			{{-1, ERROR, 2}, {54, SHIFT, 9}, },
			{{-1, ERROR, 3}, {4, SHIFT, 19}, {6, SHIFT, 20}, {29, SHIFT, 21}, {30, SHIFT, 22}, {31, SHIFT, 23}, {33, SHIFT, 24}, {52, SHIFT, 25}, {53, SHIFT, 26}, {54, SHIFT, 9}, },
			{{-1, ERROR, 4}, {4, SHIFT, 19}, {6, SHIFT, 20}, {29, SHIFT, 21}, {30, SHIFT, 22}, {31, SHIFT, 23}, {32, SHIFT, 34}, {33, SHIFT, 24}, {47, SHIFT, 35}, {48, SHIFT, 36}, {52, SHIFT, 25}, {53, SHIFT, 26}, {54, SHIFT, 9}, },
			{{-1, ERROR, 5}, {54, SHIFT, 9}, },
			{{-1, ERROR, 6}, {4, SHIFT, 19}, {6, SHIFT, 20}, {29, SHIFT, 21}, {30, SHIFT, 22}, {31, SHIFT, 23}, {32, SHIFT, 34}, {33, SHIFT, 24}, {47, SHIFT, 35}, {48, SHIFT, 36}, {52, SHIFT, 25}, {53, SHIFT, 26}, {54, SHIFT, 9}, },
			{{-1, ERROR, 7}, {4, SHIFT, 19}, {6, SHIFT, 20}, {29, SHIFT, 21}, {30, SHIFT, 22}, {31, SHIFT, 23}, {33, SHIFT, 24}, {52, SHIFT, 25}, {53, SHIFT, 26}, {54, SHIFT, 9}, },
			{{-1, ERROR, 8}, {4, SHIFT, 19}, {6, SHIFT, 20}, {29, SHIFT, 21}, {30, SHIFT, 22}, {31, SHIFT, 23}, {33, SHIFT, 24}, {52, SHIFT, 25}, {53, SHIFT, 26}, {54, SHIFT, 9}, },
			{{-1, REDUCE, 81}, },
			{{-1, ERROR, 10}, {55, ACCEPT, -1}, },
			{{-1, REDUCE, 87}, },
			{{-1, REDUCE, 3}, },
			{{-1, REDUCE, 2}, },
			{{-1, REDUCE, 34}, },
			{{-1, ERROR, 15}, {4, SHIFT, 46}, {6, SHIFT, 47}, {24, SHIFT, 48}, {27, SHIFT, 49}, {36, SHIFT, 50}, },
			{{-1, REDUCE, 1}, {0, SHIFT, 1}, {3, SHIFT, 2}, {28, SHIFT, 3}, {38, SHIFT, 4}, {41, SHIFT, 5}, {43, SHIFT, 6}, {44, SHIFT, 7}, {45, SHIFT, 8}, {54, SHIFT, 9}, },
			{{-1, ERROR, 17}, {0, SHIFT, 52}, {28, SHIFT, 53}, {38, SHIFT, 54}, {41, SHIFT, 55}, {43, SHIFT, 56}, {44, SHIFT, 57}, {45, SHIFT, 58}, {54, SHIFT, 9}, },
			{{-1, ERROR, 18}, {6, SHIFT, 61}, },
			{{-1, ERROR, 19}, {33, SHIFT, 24}, {52, SHIFT, 25}, {53, SHIFT, 26}, {54, SHIFT, 9}, },
			{{-1, ERROR, 20}, {4, SHIFT, 19}, {6, SHIFT, 20}, {29, SHIFT, 21}, {30, SHIFT, 22}, {31, SHIFT, 23}, {33, SHIFT, 24}, {52, SHIFT, 25}, {53, SHIFT, 26}, {54, SHIFT, 9}, },
			{{-1, ERROR, 21}, {6, SHIFT, 65}, },
			{{-1, ERROR, 22}, {6, SHIFT, 66}, },
			{{-1, ERROR, 23}, {6, SHIFT, 67}, },
			{{-1, REDUCE, 80}, },
			{{-1, REDUCE, 78}, },
			{{-1, REDUCE, 79}, },
			{{-1, REDUCE, 30}, {15, SHIFT, 68}, {16, SHIFT, 69}, {37, SHIFT, 70}, },
			{{-1, REDUCE, 50}, {12, SHIFT, 72}, {13, SHIFT, 73}, {14, SHIFT, 74}, },
			{{-1, REDUCE, 53}, {11, SHIFT, 75}, },
			{{-1, REDUCE, 57}, {9, SHIFT, 76}, {10, SHIFT, 77}, },
			{{-1, REDUCE, 60}, },
			{{-1, REDUCE, 62}, },
			{{-1, REDUCE, 61}, {1, SHIFT, 78}, {4, SHIFT, 79}, {6, SHIFT, 47}, },
			{{-1, ERROR, 34}, {4, SHIFT, 19}, {6, SHIFT, 20}, {29, SHIFT, 21}, {30, SHIFT, 22}, {31, SHIFT, 23}, {33, SHIFT, 24}, {47, SHIFT, 35}, {48, SHIFT, 36}, {52, SHIFT, 25}, {53, SHIFT, 26}, {54, SHIFT, 9}, },
			{{-1, REDUCE, 48}, },
			{{-1, REDUCE, 49}, },
			{{-1, ERROR, 37}, {35, SHIFT, 81}, {46, SHIFT, 82}, },
			{{-1, REDUCE, 36}, {34, SHIFT, 83}, },
			{{-1, REDUCE, 38}, },
			{{-1, REDUCE, 41}, },
			{{-1, ERROR, 41}, {15, SHIFT, 68}, {16, SHIFT, 69}, {17, SHIFT, 84}, {18, SHIFT, 85}, {19, SHIFT, 86}, {20, SHIFT, 87}, {21, SHIFT, 88}, {22, SHIFT, 89}, },
			{{-1, ERROR, 42}, {42, SHIFT, 90}, },
			{{-1, ERROR, 43}, {35, SHIFT, 81}, {46, SHIFT, 91}, },
			{{-1, REDUCE, 18}, {15, SHIFT, 68}, {16, SHIFT, 69}, {37, SHIFT, 70}, },
			{{-1, REDUCE, 16}, {15, SHIFT, 68}, {16, SHIFT, 69}, },
			{{-1, ERROR, 46}, {4, SHIFT, 19}, {6, SHIFT, 20}, {29, SHIFT, 21}, {30, SHIFT, 22}, {31, SHIFT, 23}, {33, SHIFT, 24}, {52, SHIFT, 25}, {53, SHIFT, 26}, {54, SHIFT, 9}, },
			{{-1, ERROR, 47}, {4, SHIFT, 19}, {6, SHIFT, 20}, {7, SHIFT, 95}, {29, SHIFT, 21}, {30, SHIFT, 22}, {31, SHIFT, 23}, {33, SHIFT, 24}, {52, SHIFT, 25}, {53, SHIFT, 26}, {54, SHIFT, 9}, },
			{{-1, ERROR, 48}, {4, SHIFT, 19}, {6, SHIFT, 20}, {29, SHIFT, 21}, {30, SHIFT, 22}, {31, SHIFT, 23}, {33, SHIFT, 24}, {52, SHIFT, 25}, {53, SHIFT, 26}, {54, SHIFT, 9}, },
			{{-1, ERROR, 49}, {4, SHIFT, 19}, {6, SHIFT, 20}, {29, SHIFT, 21}, {30, SHIFT, 22}, {31, SHIFT, 23}, {33, SHIFT, 24}, {52, SHIFT, 25}, {53, SHIFT, 26}, {54, SHIFT, 9}, },
			{{-1, ERROR, 50}, {4, SHIFT, 19}, {6, SHIFT, 20}, {29, SHIFT, 21}, {30, SHIFT, 22}, {31, SHIFT, 23}, {33, SHIFT, 24}, {52, SHIFT, 25}, {53, SHIFT, 26}, {54, SHIFT, 9}, },
			{{-1, REDUCE, 88}, },
			{{-1, REDUCE, 92}, },
			{{-1, ERROR, 53}, {4, SHIFT, 19}, {6, SHIFT, 20}, {29, SHIFT, 21}, {30, SHIFT, 22}, {31, SHIFT, 23}, {33, SHIFT, 24}, {52, SHIFT, 25}, {53, SHIFT, 26}, {54, SHIFT, 9}, },
			{{-1, ERROR, 54}, {4, SHIFT, 19}, {6, SHIFT, 20}, {29, SHIFT, 21}, {30, SHIFT, 22}, {31, SHIFT, 23}, {32, SHIFT, 34}, {33, SHIFT, 24}, {47, SHIFT, 35}, {48, SHIFT, 36}, {52, SHIFT, 25}, {53, SHIFT, 26}, {54, SHIFT, 9}, },
			{{-1, ERROR, 55}, {54, SHIFT, 9}, },
			{{-1, ERROR, 56}, {4, SHIFT, 19}, {6, SHIFT, 20}, {29, SHIFT, 21}, {30, SHIFT, 22}, {31, SHIFT, 23}, {32, SHIFT, 34}, {33, SHIFT, 24}, {47, SHIFT, 35}, {48, SHIFT, 36}, {52, SHIFT, 25}, {53, SHIFT, 26}, {54, SHIFT, 9}, },
			{{-1, ERROR, 57}, {4, SHIFT, 19}, {6, SHIFT, 20}, {29, SHIFT, 21}, {30, SHIFT, 22}, {31, SHIFT, 23}, {33, SHIFT, 24}, {52, SHIFT, 25}, {53, SHIFT, 26}, {54, SHIFT, 9}, },
			{{-1, ERROR, 58}, {4, SHIFT, 19}, {6, SHIFT, 20}, {29, SHIFT, 21}, {30, SHIFT, 22}, {31, SHIFT, 23}, {33, SHIFT, 24}, {52, SHIFT, 25}, {53, SHIFT, 26}, {54, SHIFT, 9}, },
			{{-1, REDUCE, 35}, },
			{{-1, ERROR, 60}, {4, SHIFT, 107}, {6, SHIFT, 47}, {24, SHIFT, 108}, {27, SHIFT, 109}, {36, SHIFT, 110}, },
			{{-1, ERROR, 61}, {7, SHIFT, 111}, {54, SHIFT, 9}, },
			{{-1, ERROR, 62}, {5, SHIFT, 114}, {37, SHIFT, 115}, },
			{{-1, ERROR, 63}, {1, SHIFT, 78}, },
			{{-1, ERROR, 64}, {7, SHIFT, 118}, {15, SHIFT, 68}, {16, SHIFT, 69}, },
			{{-1, ERROR, 65}, {54, SHIFT, 9}, },
			{{-1, ERROR, 66}, {33, SHIFT, 24}, {52, SHIFT, 25}, {53, SHIFT, 26}, {54, SHIFT, 9}, },
			{{-1, ERROR, 67}, {33, SHIFT, 24}, {52, SHIFT, 25}, {53, SHIFT, 26}, {54, SHIFT, 9}, },
			{{-1, ERROR, 68}, {4, SHIFT, 19}, {6, SHIFT, 20}, {29, SHIFT, 21}, {30, SHIFT, 22}, {31, SHIFT, 23}, {33, SHIFT, 24}, {52, SHIFT, 25}, {53, SHIFT, 26}, {54, SHIFT, 9}, },
			{{-1, ERROR, 69}, {4, SHIFT, 19}, {6, SHIFT, 20}, {29, SHIFT, 21}, {30, SHIFT, 22}, {31, SHIFT, 23}, {33, SHIFT, 24}, {52, SHIFT, 25}, {53, SHIFT, 26}, {54, SHIFT, 9}, },
			{{-1, ERROR, 70}, {4, SHIFT, 19}, {6, SHIFT, 20}, {29, SHIFT, 21}, {30, SHIFT, 22}, {31, SHIFT, 23}, {33, SHIFT, 24}, {52, SHIFT, 25}, {53, SHIFT, 26}, {54, SHIFT, 9}, },
			{{-1, REDUCE, 32}, },
			{{-1, ERROR, 72}, {4, SHIFT, 19}, {6, SHIFT, 20}, {29, SHIFT, 21}, {30, SHIFT, 22}, {31, SHIFT, 23}, {33, SHIFT, 24}, {52, SHIFT, 25}, {53, SHIFT, 26}, {54, SHIFT, 9}, },
			{{-1, ERROR, 73}, {4, SHIFT, 19}, {6, SHIFT, 20}, {29, SHIFT, 21}, {30, SHIFT, 22}, {31, SHIFT, 23}, {33, SHIFT, 24}, {52, SHIFT, 25}, {53, SHIFT, 26}, {54, SHIFT, 9}, },
			{{-1, ERROR, 74}, {4, SHIFT, 19}, {6, SHIFT, 20}, {29, SHIFT, 21}, {30, SHIFT, 22}, {31, SHIFT, 23}, {33, SHIFT, 24}, {52, SHIFT, 25}, {53, SHIFT, 26}, {54, SHIFT, 9}, },
			{{-1, ERROR, 75}, {4, SHIFT, 19}, {6, SHIFT, 20}, {29, SHIFT, 21}, {30, SHIFT, 22}, {31, SHIFT, 23}, {33, SHIFT, 24}, {52, SHIFT, 25}, {53, SHIFT, 26}, {54, SHIFT, 9}, },
			{{-1, REDUCE, 63}, },
			{{-1, REDUCE, 64}, },
			{{-1, ERROR, 78}, {54, SHIFT, 9}, },
			{{-1, ERROR, 79}, {4, SHIFT, 19}, {6, SHIFT, 20}, {29, SHIFT, 21}, {30, SHIFT, 22}, {31, SHIFT, 23}, {33, SHIFT, 24}, {52, SHIFT, 25}, {53, SHIFT, 26}, {54, SHIFT, 9}, },
			{{-1, REDUCE, 40}, },
			{{-1, ERROR, 81}, {4, SHIFT, 19}, {6, SHIFT, 20}, {29, SHIFT, 21}, {30, SHIFT, 22}, {31, SHIFT, 23}, {32, SHIFT, 34}, {33, SHIFT, 24}, {47, SHIFT, 35}, {48, SHIFT, 36}, {52, SHIFT, 25}, {53, SHIFT, 26}, {54, SHIFT, 9}, },
			{{-1, ERROR, 82}, {0, SHIFT, 1}, {28, SHIFT, 3}, {38, SHIFT, 4}, {41, SHIFT, 5}, {43, SHIFT, 6}, {44, SHIFT, 7}, {45, SHIFT, 8}, {54, SHIFT, 9}, },
			{{-1, ERROR, 83}, {4, SHIFT, 19}, {6, SHIFT, 20}, {29, SHIFT, 21}, {30, SHIFT, 22}, {31, SHIFT, 23}, {32, SHIFT, 34}, {33, SHIFT, 24}, {47, SHIFT, 35}, {48, SHIFT, 36}, {52, SHIFT, 25}, {53, SHIFT, 26}, {54, SHIFT, 9}, },
			{{-1, ERROR, 84}, {4, SHIFT, 19}, {6, SHIFT, 20}, {29, SHIFT, 21}, {30, SHIFT, 22}, {31, SHIFT, 23}, {33, SHIFT, 24}, {52, SHIFT, 25}, {53, SHIFT, 26}, {54, SHIFT, 9}, },
			{{-1, ERROR, 85}, {4, SHIFT, 19}, {6, SHIFT, 20}, {29, SHIFT, 21}, {30, SHIFT, 22}, {31, SHIFT, 23}, {33, SHIFT, 24}, {52, SHIFT, 25}, {53, SHIFT, 26}, {54, SHIFT, 9}, },
			{{-1, ERROR, 86}, {4, SHIFT, 19}, {6, SHIFT, 20}, {29, SHIFT, 21}, {30, SHIFT, 22}, {31, SHIFT, 23}, {33, SHIFT, 24}, {52, SHIFT, 25}, {53, SHIFT, 26}, {54, SHIFT, 9}, },
			{{-1, ERROR, 87}, {4, SHIFT, 19}, {6, SHIFT, 20}, {29, SHIFT, 21}, {30, SHIFT, 22}, {31, SHIFT, 23}, {33, SHIFT, 24}, {52, SHIFT, 25}, {53, SHIFT, 26}, {54, SHIFT, 9}, },
			{{-1, ERROR, 88}, {4, SHIFT, 19}, {6, SHIFT, 20}, {29, SHIFT, 21}, {30, SHIFT, 22}, {31, SHIFT, 23}, {33, SHIFT, 24}, {52, SHIFT, 25}, {53, SHIFT, 26}, {54, SHIFT, 9}, },
			{{-1, ERROR, 89}, {4, SHIFT, 19}, {6, SHIFT, 20}, {29, SHIFT, 21}, {30, SHIFT, 22}, {31, SHIFT, 23}, {33, SHIFT, 24}, {52, SHIFT, 25}, {53, SHIFT, 26}, {54, SHIFT, 9}, },
			{{-1, ERROR, 90}, {54, SHIFT, 9}, },
			{{-1, ERROR, 91}, {0, SHIFT, 1}, {28, SHIFT, 3}, {38, SHIFT, 4}, {41, SHIFT, 5}, {43, SHIFT, 6}, {44, SHIFT, 7}, {45, SHIFT, 8}, {54, SHIFT, 9}, },
			{{-1, REDUCE, 93}, },
			{{-1, REDUCE, 20}, {37, SHIFT, 70}, },
			{{-1, ERROR, 94}, {5, SHIFT, 144}, {15, SHIFT, 68}, {16, SHIFT, 69}, },
			{{-1, REDUCE, 73}, },
			{{-1, REDUCE, 75}, {15, SHIFT, 68}, {16, SHIFT, 69}, {37, SHIFT, 70}, },
			{{-1, ERROR, 97}, {7, SHIFT, 146}, },
			{{-1, REDUCE, 26}, {15, SHIFT, 68}, {16, SHIFT, 69}, },
			{{-1, REDUCE, 24}, {15, SHIFT, 68}, {16, SHIFT, 69}, },
			{{-1, REDUCE, 22}, {15, SHIFT, 68}, {16, SHIFT, 69}, },
			{{-1, REDUCE, 31}, {15, SHIFT, 68}, {16, SHIFT, 69}, {37, SHIFT, 70}, },
			{{-1, ERROR, 102}, {35, SHIFT, 81}, {46, SHIFT, 148}, },
			{{-1, ERROR, 103}, {42, SHIFT, 149}, },
			{{-1, ERROR, 104}, {35, SHIFT, 81}, {46, SHIFT, 150}, },
			{{-1, REDUCE, 19}, {15, SHIFT, 68}, {16, SHIFT, 69}, {37, SHIFT, 70}, },
			{{-1, REDUCE, 17}, {15, SHIFT, 68}, {16, SHIFT, 69}, },
			{{-1, ERROR, 107}, {4, SHIFT, 19}, {6, SHIFT, 20}, {29, SHIFT, 21}, {30, SHIFT, 22}, {31, SHIFT, 23}, {33, SHIFT, 24}, {52, SHIFT, 25}, {53, SHIFT, 26}, {54, SHIFT, 9}, },
			{{-1, ERROR, 108}, {4, SHIFT, 19}, {6, SHIFT, 20}, {29, SHIFT, 21}, {30, SHIFT, 22}, {31, SHIFT, 23}, {33, SHIFT, 24}, {52, SHIFT, 25}, {53, SHIFT, 26}, {54, SHIFT, 9}, },
			{{-1, ERROR, 109}, {4, SHIFT, 19}, {6, SHIFT, 20}, {29, SHIFT, 21}, {30, SHIFT, 22}, {31, SHIFT, 23}, {33, SHIFT, 24}, {52, SHIFT, 25}, {53, SHIFT, 26}, {54, SHIFT, 9}, },
			{{-1, ERROR, 110}, {4, SHIFT, 19}, {6, SHIFT, 20}, {29, SHIFT, 21}, {30, SHIFT, 22}, {31, SHIFT, 23}, {33, SHIFT, 24}, {52, SHIFT, 25}, {53, SHIFT, 26}, {54, SHIFT, 9}, },
			{{-1, ERROR, 111}, {46, SHIFT, 156}, },
			{{-1, ERROR, 112}, {7, SHIFT, 157}, },
			{{-1, REDUCE, 6}, {36, SHIFT, 158}, {37, SHIFT, 159}, },
			{{-1, REDUCE, 71}, },
			{{-1, ERROR, 115}, {33, SHIFT, 24}, {52, SHIFT, 25}, {53, SHIFT, 26}, {54, SHIFT, 9}, },
			{{-1, REDUCE, 95}, },
			{{-1, ERROR, 117}, {5, SHIFT, 164}, {37, SHIFT, 115}, },
			{{-1, REDUCE, 70}, },
			{{-1, ERROR, 119}, {7, SHIFT, 166}, },
			{{-1, ERROR, 120}, {7, SHIFT, 167}, {37, SHIFT, 115}, },
			{{-1, ERROR, 121}, {7, SHIFT, 169}, {37, SHIFT, 115}, },
			{{-1, REDUCE, 51}, {12, SHIFT, 72}, {13, SHIFT, 73}, {14, SHIFT, 74}, },
			{{-1, REDUCE, 52}, {12, SHIFT, 72}, {13, SHIFT, 73}, {14, SHIFT, 74}, },
			{{-1, REDUCE, 82}, {15, SHIFT, 68}, {16, SHIFT, 69}, },
			{{-1, REDUCE, 54}, {11, SHIFT, 75}, },
			{{-1, REDUCE, 55}, {11, SHIFT, 75}, },
			{{-1, REDUCE, 56}, {11, SHIFT, 75}, },
			{{-1, REDUCE, 58}, {9, SHIFT, 76}, {10, SHIFT, 77}, },
			{{-1, REDUCE, 77}, },
			{{-1, ERROR, 130}, {6, SHIFT, 47}, },
			{{-1, ERROR, 131}, {5, SHIFT, 171}, {15, SHIFT, 68}, {16, SHIFT, 69}, },
			{{-1, REDUCE, 37}, {34, SHIFT, 83}, },
			{{-1, REDUCE, 10}, },
			{{-1, REDUCE, 39}, },
			{{-1, REDUCE, 47}, {15, SHIFT, 68}, {16, SHIFT, 69}, },
			{{-1, REDUCE, 46}, {15, SHIFT, 68}, {16, SHIFT, 69}, },
			{{-1, REDUCE, 45}, {15, SHIFT, 68}, {16, SHIFT, 69}, },
			{{-1, REDUCE, 44}, {15, SHIFT, 68}, {16, SHIFT, 69}, },
			{{-1, REDUCE, 43}, {15, SHIFT, 68}, {16, SHIFT, 69}, },
			{{-1, REDUCE, 42}, {15, SHIFT, 68}, {16, SHIFT, 69}, },
			{{-1, ERROR, 141}, {46, SHIFT, 172}, },
			{{-1, REDUCE, 12}, },
			{{-1, REDUCE, 94}, },
			{{-1, ERROR, 144}, {36, SHIFT, 173}, },
			{{-1, REDUCE, 76}, {37, SHIFT, 70}, },
			{{-1, REDUCE, 74}, },
			{{-1, REDUCE, 33}, },
			{{-1, ERROR, 148}, {0, SHIFT, 1}, {28, SHIFT, 3}, {38, SHIFT, 4}, {41, SHIFT, 5}, {43, SHIFT, 6}, {44, SHIFT, 7}, {45, SHIFT, 8}, {54, SHIFT, 9}, },
			{{-1, ERROR, 149}, {54, SHIFT, 9}, },
			{{-1, ERROR, 150}, {0, SHIFT, 1}, {28, SHIFT, 3}, {38, SHIFT, 4}, {41, SHIFT, 5}, {43, SHIFT, 6}, {44, SHIFT, 7}, {45, SHIFT, 8}, {54, SHIFT, 9}, },
			{{-1, REDUCE, 21}, {37, SHIFT, 70}, },
			{{-1, ERROR, 152}, {5, SHIFT, 177}, {15, SHIFT, 68}, {16, SHIFT, 69}, },
			{{-1, REDUCE, 27}, {15, SHIFT, 68}, {16, SHIFT, 69}, },
			{{-1, REDUCE, 25}, {15, SHIFT, 68}, {16, SHIFT, 69}, },
			{{-1, REDUCE, 23}, {15, SHIFT, 68}, {16, SHIFT, 69}, },
			{{-1, ERROR, 156}, {0, SHIFT, 1}, {28, SHIFT, 3}, {38, SHIFT, 4}, {41, SHIFT, 5}, {43, SHIFT, 6}, {44, SHIFT, 7}, {45, SHIFT, 8}, {54, SHIFT, 9}, },
			{{-1, ERROR, 157}, {46, SHIFT, 179}, },
			{{-1, ERROR, 158}, {33, SHIFT, 24}, {52, SHIFT, 25}, {53, SHIFT, 26}, {54, SHIFT, 9}, },
			{{-1, ERROR, 159}, {54, SHIFT, 9}, },
			{{-1, REDUCE, 7}, {37, SHIFT, 159}, },
			{{-1, REDUCE, 89}, },
			{{-1, REDUCE, 8}, {37, SHIFT, 159}, },
			{{-1, REDUCE, 83}, },
			{{-1, REDUCE, 72}, },
			{{-1, REDUCE, 96}, },
			{{-1, REDUCE, 65}, },
			{{-1, REDUCE, 66}, },
			{{-1, ERROR, 168}, {7, SHIFT, 184}, {37, SHIFT, 115}, },
			{{-1, REDUCE, 68}, },
			{{-1, ERROR, 170}, {7, SHIFT, 185}, {37, SHIFT, 115}, },
			{{-1, REDUCE, 59}, },
			{{-1, ERROR, 172}, {0, SHIFT, 1}, {28, SHIFT, 3}, {38, SHIFT, 4}, {41, SHIFT, 5}, {43, SHIFT, 6}, {44, SHIFT, 7}, {45, SHIFT, 8}, {54, SHIFT, 9}, },
			{{-1, ERROR, 173}, {4, SHIFT, 19}, {6, SHIFT, 20}, {29, SHIFT, 21}, {30, SHIFT, 22}, {31, SHIFT, 23}, {33, SHIFT, 24}, {52, SHIFT, 25}, {53, SHIFT, 26}, {54, SHIFT, 9}, },
			{{-1, REDUCE, 11}, },
			{{-1, ERROR, 175}, {46, SHIFT, 188}, },
			{{-1, REDUCE, 13}, },
			{{-1, ERROR, 177}, {36, SHIFT, 189}, },
			{{-1, REDUCE, 4}, },
			{{-1, ERROR, 179}, {0, SHIFT, 1}, {28, SHIFT, 3}, {38, SHIFT, 4}, {41, SHIFT, 5}, {43, SHIFT, 6}, {44, SHIFT, 7}, {45, SHIFT, 8}, {54, SHIFT, 9}, },
			{{-1, REDUCE, 84}, },
			{{-1, REDUCE, 85}, {36, SHIFT, 158}, },
			{{-1, REDUCE, 9}, {37, SHIFT, 159}, },
			{{-1, REDUCE, 90}, },
			{{-1, REDUCE, 67}, },
			{{-1, REDUCE, 69}, },
			{{-1, REDUCE, 14}, },
			{{-1, REDUCE, 28}, {15, SHIFT, 68}, {16, SHIFT, 69}, },
			{{-1, ERROR, 188}, {0, SHIFT, 1}, {28, SHIFT, 3}, {38, SHIFT, 4}, {41, SHIFT, 5}, {43, SHIFT, 6}, {44, SHIFT, 7}, {45, SHIFT, 8}, {54, SHIFT, 9}, },
			{{-1, ERROR, 189}, {4, SHIFT, 19}, {6, SHIFT, 20}, {29, SHIFT, 21}, {30, SHIFT, 22}, {31, SHIFT, 23}, {33, SHIFT, 24}, {52, SHIFT, 25}, {53, SHIFT, 26}, {54, SHIFT, 9}, },
			{{-1, REDUCE, 5}, },
			{{-1, REDUCE, 86}, },
			{{-1, REDUCE, 15}, },
			{{-1, REDUCE, 29}, {15, SHIFT, 68}, {16, SHIFT, 69}, },
        };*/
    private static int[][][] gotoTable;
/*      {
			{{-1, 10}, },
			{{-1, 11}, {16, 51}, },
			{{-1, 12}, },
			{{-1, 112}, },
			{{-1, 13}, {82, 133}, {91, 142}, {148, 174}, {150, 176}, {156, 178}, {172, 186}, {179, 190}, {188, 192}, },
			{{-1, 37}, {6, 43}, {54, 102}, {56, 104}, },
			{{-1, 38}, {81, 132}, },
			{{-1, 39}, {83, 134}, },
			{{-1, 40}, {34, 80}, },
			{{-1, 41}, {3, 27}, {7, 44}, {8, 45}, {20, 64}, {46, 94}, {47, 96}, {48, 98}, {49, 99}, {50, 100}, {53, 101}, {57, 105}, {58, 106}, {70, 124}, {79, 131}, {84, 135}, {85, 136}, {86, 137}, {87, 138}, {88, 139}, {89, 140}, {107, 152}, {108, 153}, {109, 154}, {110, 155}, {173, 187}, {189, 193}, },
			{{-1, 28}, {68, 122}, {69, 123}, },
			{{-1, 29}, {72, 125}, {73, 126}, {74, 127}, },
			{{-1, 30}, {75, 128}, },
			{{-1, 31}, {0, 14}, {16, 14}, {17, 59}, {78, 129}, {82, 14}, {91, 14}, {148, 14}, {150, 14}, {156, 14}, {172, 14}, {179, 14}, {188, 14}, },
			{{-1, 97}, },
			{{-1, 32}, {19, 62}, {66, 120}, {67, 121}, {115, 163}, {158, 180}, },
			{{-1, 33}, {0, 15}, {2, 18}, {5, 42}, {16, 15}, {17, 60}, {19, 63}, {55, 103}, {61, 113}, {65, 119}, {66, 63}, {67, 63}, {78, 130}, {82, 15}, {90, 141}, {91, 15}, {115, 63}, {148, 15}, {149, 175}, {150, 15}, {156, 15}, {158, 63}, {159, 181}, {172, 15}, {179, 15}, {188, 15}, },
			{{-1, 92}, {27, 71}, {93, 143}, {101, 147}, {145, 143}, {151, 143}, },
			{{-1, 116}, {117, 165}, {168, 165}, {170, 165}, },
			{{-1, 160}, {181, 191}, },
			{{-1, 161}, {162, 183}, {182, 183}, },
			{{-1, 16}, },
			{{-1, 162}, {160, 182}, },
			{{-1, 17}, },
			{{-1, 93}, {96, 145}, {105, 151}, },
			{{-1, 117}, {120, 168}, {121, 170}, },
        };*/
    private static String[] errorMessages;
/*      {
			"expecting: tab, 'def', 'assert', 'if', 'for', 'while', 'print', 'return', id, EOF",
			"expecting: tab, 'assert', 'if', 'for', 'while', 'print', 'return', id",
			"expecting: id",
			"expecting: '[', '(', 'len', 'max', 'min', 'None', number, string, id",
			"expecting: '[', '(', 'len', 'max', 'min', 'not', 'None', 'true', 'false', number, string, id",
			"expecting: tab, dot, 'def', '[', ']', '(', ')', '++', '--', '**', '*', '/', '%', '+', '-', '==', '!=', '<=', '>=', '<', '>', '/=', '-=', 'assert', 'and', 'or', '=', ',', 'if', 'for', 'in', 'while', 'print', 'return', ':', id, EOF",
			"expecting: EOF",
			"expecting: '[', '(', '/=', '-=', '='",
			"expecting: '('",
			"expecting: 'None', number, string, id",
			"expecting: tab, 'def', ']', ')', '++', '--', '**', '*', '/', '%', '+', '-', '==', '!=', '<=', '>=', '<', '>', 'assert', 'and', 'or', ',', 'if', 'for', 'while', 'print', 'return', ':', id, EOF",
			"expecting: tab, 'def', '+', '-', 'assert', ',', 'if', 'for', 'while', 'print', 'return', id, EOF",
			"expecting: tab, 'def', ']', ')', '*', '/', '%', '+', '-', '==', '!=', '<=', '>=', '<', '>', 'assert', 'and', 'or', ',', 'if', 'for', 'while', 'print', 'return', ':', id, EOF",
			"expecting: tab, 'def', ']', ')', '**', '*', '/', '%', '+', '-', '==', '!=', '<=', '>=', '<', '>', 'assert', 'and', 'or', ',', 'if', 'for', 'while', 'print', 'return', ':', id, EOF",
			"expecting: tab, dot, 'def', '[', ']', '(', ')', '++', '--', '**', '*', '/', '%', '+', '-', '==', '!=', '<=', '>=', '<', '>', 'assert', 'and', 'or', ',', 'if', 'for', 'while', 'print', 'return', ':', id, EOF",
			"expecting: '[', '(', 'len', 'max', 'min', 'None', 'true', 'false', number, string, id",
			"expecting: 'and', 'or', ':'",
			"expecting: 'or', ':'",
			"expecting: '+', '-', '==', '!=', '<=', '>=', '<', '>'",
			"expecting: 'in'",
			"expecting: tab, 'def', '+', '-', 'assert', 'if', 'for', 'while', 'print', 'return', id, EOF",
			"expecting: '[', '(', ')', 'len', 'max', 'min', 'None', number, string, id",
			"expecting: ')', id",
			"expecting: ']', ','",
			"expecting: dot",
			"expecting: ')', '+', '-'",
			"expecting: tab, 'def', ')', 'assert', ',', 'if', 'for', 'while', 'print', 'return', id, EOF",
			"expecting: tab, 'def', 'assert', ',', 'if', 'for', 'while', 'print', 'return', id, EOF",
			"expecting: ']', '+', '-'",
			"expecting: ')', '+', '-', ','",
			"expecting: ')'",
			"expecting: ':'",
			"expecting: ')', '=', ','",
			"expecting: ']', ')', ','",
			"expecting: ')', ','",
			"expecting: tab, 'def', ')', '+', '-', 'assert', ',', 'if', 'for', 'while', 'print', 'return', id, EOF",
			"expecting: '+', '-', 'and', 'or', ':'",
			"expecting: '='",
        };*/
    private static int[] errors;
/*      {
			0, 1, 2, 3, 4, 2, 4, 3, 3, 5, 6, 0, 0, 0, 0, 7, 0, 1, 8, 9, 3, 8, 8, 8, 10, 10, 10, 11, 12, 13, 10, 10, 10, 14, 15, 16, 16, 17, 16, 16, 16, 18, 19, 17, 11, 20, 3, 21, 3, 3, 3, 0, 1, 3, 4, 2, 4, 3, 3, 0, 7, 22, 23, 24, 25, 2, 9, 9, 3, 3, 3, 0, 3, 3, 3, 3, 10, 10, 2, 3, 16, 4, 1, 4, 3, 3, 3, 3, 3, 3, 2, 1, 26, 27, 28, 10, 29, 30, 20, 20, 20, 11, 17, 19, 17, 11, 20, 3, 3, 3, 3, 31, 30, 32, 10, 9, 33, 23, 10, 30, 34, 34, 12, 12, 35, 13, 13, 13, 10, 10, 8, 28, 16, 0, 16, 36, 36, 36, 36, 36, 36, 31, 0, 26, 37, 34, 10, 0, 1, 2, 1, 27, 28, 20, 20, 20, 1, 31, 9, 2, 34, 34, 34, 33, 10, 33, 10, 10, 34, 10, 34, 10, 1, 3, 0, 31, 0, 37, 0, 1, 34, 32, 34, 34, 10, 10, 0, 20, 1, 3, 0, 34, 0, 20, 
        };*/
}
