/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.parser;

import minipython.node.*;
import minipython.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    public void caseTTab(TTab node)
    {
        index = 0;
    }

    public void caseTDot(TDot node)
    {
        index = 1;
    }

    public void caseTClassToken(TClassToken node)
    {
        index = 2;
    }

    public void caseTDef(TDef node)
    {
        index = 3;
    }

    public void caseTLSqBrack(TLSqBrack node)
    {
        index = 4;
    }

    public void caseTRSqBrack(TRSqBrack node)
    {
        index = 5;
    }

    public void caseTLPar(TLPar node)
    {
        index = 6;
    }

    public void caseTRPar(TRPar node)
    {
        index = 7;
    }

    public void caseTExclam(TExclam node)
    {
        index = 8;
    }

    public void caseTPlusplus(TPlusplus node)
    {
        index = 9;
    }

    public void caseTMinmin(TMinmin node)
    {
        index = 10;
    }

    public void caseTDmult(TDmult node)
    {
        index = 11;
    }

    public void caseTMult(TMult node)
    {
        index = 12;
    }

    public void caseTDiv(TDiv node)
    {
        index = 13;
    }

    public void caseTMod(TMod node)
    {
        index = 14;
    }

    public void caseTPlus(TPlus node)
    {
        index = 15;
    }

    public void caseTMinus(TMinus node)
    {
        index = 16;
    }

    public void caseTEqeq(TEqeq node)
    {
        index = 17;
    }

    public void caseTNoteq(TNoteq node)
    {
        index = 18;
    }

    public void caseTLesseq(TLesseq node)
    {
        index = 19;
    }

    public void caseTMoreeq(TMoreeq node)
    {
        index = 20;
    }

    public void caseTLess(TLess node)
    {
        index = 21;
    }

    public void caseTGreat(TGreat node)
    {
        index = 22;
    }

    public void caseTLogicAnd(TLogicAnd node)
    {
        index = 23;
    }

    public void caseTDiveq(TDiveq node)
    {
        index = 24;
    }

    public void caseTMulteq(TMulteq node)
    {
        index = 25;
    }

    public void caseTPluseq(TPluseq node)
    {
        index = 26;
    }

    public void caseTMineq(TMineq node)
    {
        index = 27;
    }

    public void caseTAssert(TAssert node)
    {
        index = 28;
    }

    public void caseTLen(TLen node)
    {
        index = 29;
    }

    public void caseTMax(TMax node)
    {
        index = 30;
    }

    public void caseTMin(TMin node)
    {
        index = 31;
    }

    public void caseTNot(TNot node)
    {
        index = 32;
    }

    public void caseTNone(TNone node)
    {
        index = 33;
    }

    public void caseTAnd(TAnd node)
    {
        index = 34;
    }

    public void caseTOr(TOr node)
    {
        index = 35;
    }

    public void caseTEq(TEq node)
    {
        index = 36;
    }

    public void caseTComma(TComma node)
    {
        index = 37;
    }

    public void caseTIf(TIf node)
    {
        index = 38;
    }

    public void caseTElif(TElif node)
    {
        index = 39;
    }

    public void caseTElse(TElse node)
    {
        index = 40;
    }

    public void caseTFor(TFor node)
    {
        index = 41;
    }

    public void caseTIn(TIn node)
    {
        index = 42;
    }

    public void caseTWhile(TWhile node)
    {
        index = 43;
    }

    public void caseTPrint(TPrint node)
    {
        index = 44;
    }

    public void caseTReturn(TReturn node)
    {
        index = 45;
    }

    public void caseTSemi(TSemi node)
    {
        index = 46;
    }

    public void caseTTrue(TTrue node)
    {
        index = 47;
    }

    public void caseTFalse(TFalse node)
    {
        index = 48;
    }

    public void caseTDictt(TDictt node)
    {
        index = 49;
    }

    public void caseTQuote(TQuote node)
    {
        index = 50;
    }

    public void caseTSinquote(TSinquote node)
    {
        index = 51;
    }

    public void caseTNumber(TNumber node)
    {
        index = 52;
    }

    public void caseTString(TString node)
    {
        index = 53;
    }

    public void caseTId(TId node)
    {
        index = 54;
    }

    public void caseEOF(EOF node)
    {
        index = 55;
    }
}
